# this file defines multistages for different environments
# To add more stages, uncomment and rename to reflect the env. configuration you need 

stages:
#- template: 01_deployment-stage.yml
#  parameters:
#    STAGE_NAME: development
#    STAGE_ENVIRONMENT: $(DEV_ENVIRONMENT_NAME)
#    STAGE_K8S_SERVICE_ENDPOINT: $(DEV_CLUSTER_SERVICE_CONNECTION_NAME)

- template: 01_deployment-stage.yml
  parameters:
    STAGE_NAME: test
    STAGE_ENVIRONMENT: $(TEST_ENVIRONMENT_NAME)
    STAGE_K8S_SERVICE_ENDPOINT: $(TEST_CLUSTER_SERVICE_CONNECTION_NAME)

#- template: 01_deployment-stage.yml
#  parameters:
#    STAGE_NAME: production
#    STAGE_ENVIRONMENT: $(PROD_ENVIRONMENT_NAME)
#    STAGE_K8S_SERVICE_ENDPOINT: $(PROD_CLUSTER_SERVICE_CONNECTION_NAME)

