parameters:
  STAGE_NAME: ''
  STAGE_ENVIRONMENT: ''
  STAGE_K8S_SERVICE_ENDPOINT: ''

stages:
- stage: ${{ parameters.STAGE_NAME }}
  jobs:  
  - deployment: SetupCluster
    pool: 
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.STAGE_ENVIRONMENT }}
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: yaml
              targetPath: $(Build.SourcesDirectory)

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: '2.14.3'

          - task: Kubernetes@1
            displayName: Configure custom role
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: ${{ parameters.STAGE_K8S_SERVICE_ENDPOINT }}
              command: 'apply'
              arguments: '-f $(Build.SourcesDirectory)/02_configure-custom-role.yaml'

          - task: Kubernetes@1
            displayName: Apply Hello World
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: ${{ parameters.STAGE_K8S_SERVICE_ENDPOINT }}
              namespace: ${{ parameters.STAGE_ENVIRONMENT }}
              command: 'apply'
              arguments: '-f $(Build.SourcesDirectory)/03_aks-helloworld.yaml'
          
          - task: Kubernetes@1
            displayName: Apply Azure Vote
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: ${{ parameters.STAGE_K8S_SERVICE_ENDPOINT }}
              namespace: ${{ parameters.STAGE_ENVIRONMENT }}
              command: 'apply'
              arguments: '-f $(Build.SourcesDirectory)/04_azure_vote.yaml'

          - task: Bash@3
            displayName: "Repo update"
            inputs:
              targetType: 'inline'
              script: 'helm repo update'  

          - task: Bash@3
            displayName: "echo staging"
            inputs:
              targetType: 'inline'
              script: 'echo ${{ parameters.STAGE_ENVIRONMENT }}'