variables:
- group: kubernetes-on-azure

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest' 
    continueOnError: true
    steps:
    - checkout: self
      clean: true
      persistCredentials: true 
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)
        artifact: yaml

- template: 00_deploy-to-all-stages.yml