apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: ingress-basic
spec:
  secretName: tls-secret
  dnsNames:
  - superusers2020.westeurope.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - superusers2020.westeurope.cloudapp.azure.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer